### ISSUE TITLE
There are some errors 

### ISSUE THREAD

**Issue by FryLcm** [clientSideGIA/CGI#1]
target_number variable not found in Main_framework_lib3.py file
![image](https://github.com/clientSideGIA/PGLC/assets/60080577/0ff6777c-f322-40bf-8abb-d1904a3b4074)

**Comment by FryLcm** [comment]
IMCapture variable not found in gradient_lib.py file
![image](https://github.com/clientSideGIA/PGLC/assets/60080577/9f0d7d7f-9c58-4960-b4aa-9c72ea9feec5)

**Comment by clientSideGIA** [comment]
No worries, these errors are debugging or test code that never used in the published program. We have fixed them.
